version: "3"

services:
  web01:
    container_name: ego_web
    hostname: ego_web
    ports:
      - "9003:8080"
    build:
      context: ..
    env_file:
      - ../config/.env.dev
    deploy:
      mode: replicated
      replicas: 1
    networks:
      - docker_network

networks: # 가장 기본적인 bridge 네트워크 test
  docker_network:
    driver: bridge
    external: true